portal:
  debug: true

log:
  logdir: /var/log/sdcc
  verbosity: DEBUG

db:
  db: sdcc
  host: mongo
  port: 27017
  user:
  password:

statistics:
  db: sdcc
  host: mongo
  port: 27017
  user:
  password:

rb:
  db: sdcc
  host: mongo
  port: 27017
  user:
  password:

backend:
  name: docker
  role: hybrid
