console.log([
  'DP Isolate fixture commands',
  '',
  'List local fixture archives:',
  '  npm run dp-isolate-fixtures:list',
  '',
  'Capture the current local Mongo container into a named fixture:',
  '  npm run dp-isolate-fixtures:capture -- <name> [--description "..."] [--force] [--container name] [--db sdcc]',
  '',
  'Restore a named local fixture into the local Mongo container:',
  '  npm run dp-isolate-fixtures:restore -- <name> --yes [--container name] [--db sdcc]',
  '  npm run dp-isolate-fixtures:restore -- <name> --yes --preset dp-isolate',
  '  npm run dp-isolate-fixtures:restore -- <name> --yes --collections DPZones,Incidents,Tasks',
  '',
  'Restore from the clean source DB without capturing the current local state:',
  '  npm run dp-isolate-fixtures:restore-clean -- --yes [--source-uri mongodb://host:port/sdcc] [--container name] [--db sdcc]',
  '',
  'Defaults:',
  '  container: legacy-portal-mongo-1',
  '  db: sdcc',
  '  clean source: mongodb://10.20.4.110:27017/sdcc',
  '',
  'Environment overrides:',
  '  LEGACY_PORTAL_MONGO_CONTAINER',
  '  SDCC_MONGO_DB',
  '  DP_ISOLATE_CLEAN_MONGO_URI',
  '',
  'Safety notes:',
  '  capture writes a local fixture from the current DB state.',
  '  restore and restore-clean are destructive and require --yes.',
  '  restore with --preset or --collections drops/restores only those collections.',
].join('\n'));
